services:
  - type: web
    name: unimarket
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Main:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
