services:
  - type: web
    name: unimarket
    env: docker
    dockerfilePath: Dockerfile
    branch: main
    region: oregon   
    plan: free      
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_1f5QsLqxWyEb@ep-proud-butterfly-a4w83qe1-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
